# Generated by Django 4.2.3 on 2023-08-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/student'),
        ),
    ]
