# Generated by Django 4.2.3 on 2023-08-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_rename_mobilno_employee_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobileno',
            field=models.CharField(max_length=50),
        ),
    ]
